### ISSUE TITLE
About the Sample Algorithm introduced on purchase dataset

### ISSUE THREAD

**Issue by KaimingZhu** [csong27/membership-inference#11]
Hi, Dr. Song. I am now working on the privacy of federated learning, and I have read the article _Membership Inference Attacks Against Machine Learning Models_ . It is very kind of you for sharing the source code.

But I have found my recurrence of attack on purchase dataset don't work well. Could you share the detail of sample algorithm of the simplified purchase dataset? I have found that each commodity are represented as `dept, category, company, brand` . And I am doubting in these following question : 

- If this code is for the attack on purchase dataset?
- The primary key represent a certain commodity is composed by four parts . Do you remember which commodity feature you have used to represent the simplified primary key of each commodity ? 
- I have found that you used 600 feature from the commodity list. Can I understand like that : After random sampling on the purchase dataset, we randomly choose 600 columns of the matrix represent which commodity the user has bought. After that, we begin our k-means clustering algorithm, give each input a label?

Thank you for all your assistance.

**Comment by csong27** [comment]
Please refer to https://github.com/privacytrustlab/ml_privacy_meter for the dataset we used in the paper

**Comment by KaimingZhu** [comment]
> Please refer to https://github.com/privacytrustlab/ml_privacy_meter for the dataset we used in the paper

Thanks a lot :)
