### ISSUE TITLE
Attack model for already trained model

### ISSUE THREAD

**Issue by mhsamavatian** [csong27/membership-inference#4]
Hi,
I am not an AI expert and I need to train your attack model. I am a little bit confused here.
Why do you train a target model? Isn't the target model the one provided by MLAAS or at least the attacker does not know about.
In other words, I have a trained model with inputs and outputs. I just need to train the shadow model and the attack model. Do I still need to train the target model again?
If not what do I have to change in the code?
Thanks

**Comment by csong27** [comment]
Hi, we train the target model locally to "simulate" MLAAS. You can modify the code to replace with your trained target model.
